import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
// import HeroSection from "./components/HeroSection";
import CarousalHeader from "./components/CarousalHeader";
import CarousalHomepage from "./components/CarousalHomepage";
import Heroine from "./components/HeroineSection";
import AchievementHomepage from "./components/AchievementHomepage";
import Footer from "./components/Footer";
// import AchievementHomepage from "@/app/components/AchievementHomepage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        <CarousalHeader />
        <CarousalHomepage />
        <Heroine />
        <AchievementHomepage />
        <main>{children}</main> {/* Ensure children render properly */}
        <Footer />
      </body>
    </html>
  );
}
